### ISSUE TITLE
Make VideoTopic Great Again!

### ISSUE THREAD

**Issue by juliusvdijk** [RUGSoftEng/2018-Tuberculosis-WebApp#38]
Please split up topic from Video into a different table.
This way we can associate more data to the topic such as a thumbnail. 
It is not 100% if we need this but that way it can be added a lot easier in the future.

Example DB:
VideoTopic
- id
- topic

Video
- (current fields minus topic)
- topic_id (FK to VideoTopic)

**Comment by StenSipma** [comment]
I think this is a good idea if we need to add more information! I think it will be best to leave it for now, but once we have more information we want to store in relation to topics, we can change it.

**Comment by StenSipma** [comment]
Okay, so the main problem with this is that topics are not used, because the video's aren't grouped into topics. I guess i'll just close this because of this reason.
